# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
- id: yaml2go
  binary: yaml2go
  main: cmd/cli/main.go
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GO_EXTLINK_ENABLED=0
- id: yaml2go_serve
  binary: yaml2go_serve
  main: cmd/serve/server.go
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GO_EXTLINK_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
